openapi: 3.0.3
info:
  title: Petstore API
  version: 1.0.0

paths:
  /pets:
    get:
      summary: List pets
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              examples:
                sample:
                  value:
                    - id: 1
                      name: "Bella"
                      tag: "DOG"
                    - id: 2
                      name: "Max"
                      tag: "CAT"
                    - id: 3
                      name: "Charlie"
                      tag: "BIRD"
                    - id: 4
                      name: "Lucy"
                      tag: "RABBIT"
                    - id: 5
                      name: "Rocky"
                      tag: "DOG"

  /pets/{petId}:
    get:
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pet found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              examples:
                dog:
                  value:
                    id: 1
                    name: "Bella"
                    tag: "DOG"
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                notFound:
                  value:
                    code: "NOT_FOUND"
                    message: "Pet not found"

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
